source "https://rubygems.org"

gem "rails", "~> 8.1.3"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false

# Functionality
gem "bcrypt", "~> 3.1.7"
gem "rack-cors"
gem "pagy"
gem "alba"
gem "action_policy"
gem "ar_lazy_preload"
gem "rack-attack"
gem "rswag-api"
gem "rswag-ui"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
end

group :test do
  gem "rswag-specs"
  gem "rspec-rails"
  gem "factory_bot_rails"
end
